### ISSUE TITLE
bittrex MarketSymbolIsReversed = true or false?

### ISSUE THREAD

**Issue by username77** [jjxtra/ExchangeSharp#537]
I used before (v0.6.x) on my side this format "BTC-ADA" but if i try to convert for exchange use using GlobalMarketSymbolToExchangeMarketSymbolAsync("BTC-ADA") i got "ADA-BTC" instead of "BTC-ADA" because "MarketSymbolIsReversed = true".  

is something changed on latest versions or is an issue?

**Comment by nh43de** [comment]
See #500 

But the idea here is that the global pair string that you're probably looking for is ADA-BTC. Meaning: 1 ADA is worth 0.000x BTC.

Bittrex reverses the quote pairs, so they list this pair as BTC-ADA, which is read 1 BTC is worth xxxxx ADA, not correct really since they quote in btc (BASE-QUOTE is convention).

So if you take GlobalMarketSymbolToExchangeMarketSymbolAsync("ADA-BTC") you should get "BTC-ADA" for bittrex.

**Comment by jjxtra** [comment]
Agreed. Standard is to do base-quote currency and use a conversion function in case your exchange is backwards.
